Epoch: 3000
Buffer Size: 1024
Batch Size: 256
Step/Epoch: 1000
Step/Collect: 1024
Repeat/Collect: 10
Learning Rate: 3.0e-4
Gamma: 0.99
Value Coefficient: 0.25
Entropy Coefficient: 0.0
GAE Lambda: 0.95
Clip: 0.2
Dual Clip: ~
Training Envs: 16
Test Envs: 4
Max Grad Norm: 0.5
Epsilon Clip: 0.15
Value Clip: 0
Recompute Advantage: 1
Advantage Normalization: 0
Reward Nomalization: True
Learning Rate Decay: True
Initial Sigma: -1.5
